name: Docker Workflow - React Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-and-push:
    runs-on: ubuntu-latest
    environment: devops-training

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Debug Dockerfile presence (to confirm path)
      - name: Debug Dockerfile presence
        run: |
          echo "Listing files in the react-docker directory:"
          ls -al ./react-docker

      # Step 4: Build and Tag Docker Image
      - name: Build and Tag Docker Image
        run: |
          docker build -f ./react-docker/dockerfile \
            -t "${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:${{ vars.IMAGE_TAG }}" ./react-docker

      # Step 5: Push to Docker Hub
      - name: Push to Docker Hub
        run: |
          docker push "${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:${{ vars.IMAGE_TAG }}"
